# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fishfingr.github.io
title: fishfingr.io
email: derp@domain.com
author: fishfinger.io
description:
copyright: 'Copyright &copy; 2015 fishfingr.io'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>. Photo: <a href="https://www.flickr.com/photos/adactio/3562925113/">Fish finger Sandwich</a> by <a href="https://www.flickr.com/photos/adactio/">Jeremy Keith</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/fishfingr
